### ISSUE TITLE
[TV emulator] cmap table size error on app launch

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#104]
The following error message is displayed right after launching an app on TV emulators:

```
E/ConsoleMessage(12522): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/ConsoleMessage(12522):

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Offset argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 52 pos 10: '<optimized out>'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  MaterialApp file:///home/swift/Git/flutter/dummy/amuapp/lib/main.dart:11:12

When the exception was thrown, this was the stack:
#2      _offsetIsValid (dart:ui/painting.dart:52:10)
#3      Canvas.drawParagraph (dart:ui/painting.dart:4384:12)
#4      TextPainter.paint (package:flutter/src/painting/text_painter.dart:624:12)
#5      BannerPainter.paint (package:flutter/src/widgets/banner.dart:147:18)
#6      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:564:13)
#7      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:610:7)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#13     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#16     RenderView.paint (package:flutter/src/rendering/view.dart:200:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
#18     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#19     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#20     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
#21     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#26     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderCustomPaint#384b9:
  needs compositing
  creator: CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ←
    _LocalizationsScope-[GlobalKey#3ad37] ← Semantics ← Localizations ← MediaQuery ←
    _MediaQueryFromWindow ← _FocusMarker ← Focus ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1200.0, h=675.0)
  size: Size(1200.0, 675.0)
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderPointerListener#fb3dd
      child: RenderAbsorbPointer#68c72
        child: RenderSemanticsAnnotations#d8eed
          child: _RenderTheatre#a58d9
            onstage 1: RenderIgnorePointer#95ef1
            onstage 2: RenderSemanticsAnnotations#f7fb7
            no offstage children
════════════════════════════════════════════════════════════════════════════════════════════════════
```
This could be related to the recent change in the engine code: https://github.com/flutter-tizen/engine/pull/69

**Comment by swift-kim** [comment]
Fixed by enabling fontconfig (https://github.com/flutter-tizen/engine/pull/122). Closing.
