### ISSUE TITLE
Cannot extract a non-Windows file path from a file URI with an authority

### ISSUE THREAD

**Issue by g123k** [flutter-tizen/flutter-tizen#116]
Hello,

I have first followed [the instructions](https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/macos-install.md) to install `flutter-tizen` on my Mac: 

But when I try to launch `flutter-tizen doctor -v`, I have the following error:

```
Building flutter tool...
kernel-service: Error: Unhandled exception:
Invalid argument(s): Exception when reading 'file://users/g123k/Documents/flutter-tizen/flutter/packages/flutter_tools/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:598:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:612:26)
<asynchronous suspension>
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:677:11)
<asynchronous suspension>
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:546:26)
<asynchronous suspension>
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:500:32)
<asynchronous suspension>
#5      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:60:35)
<asynchronous suspension>
#6      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:40:10)
<asynchronous suspension>
#7      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:149:7)
<asynchronous suspension>
#8      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:557:18)
<asynchronous suspension>
#9      _processLoadRequest (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:828:5)
<asynchronous suspension>
```

Any idea?

**Comment by swift-kim** [comment]
https://github.com/flutter/flutter/issues/63579
https://github.com/flutter/flutter/issues/71274

There are similar issues in the flutter repo and the error seems to be related to the PATH environment variable. I was able to reproduce the same issue on macOS 11.2.3 by adding an extra slash (`/`) to the variable:

```sh
export PATH=//Users/swift/Git/flutter-tizen/bin:$PATH  <- ugh!

export PATH=/Users/swift/Git/flutter-tizen/bin:$PATH   <- good!
```

Could you check if your `~/.zshrc` file has been configured properly?

**Comment by swift-kim** [comment]
Please leave a comment if the issue persists.
