### ISSUE TITLE
flutter-tizen cmd error

### ISSUE THREAD

**Issue by almog228** [flutter-tizen/flutter-tizen#132]
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "C:\Users\mos_s\flutter-tizen\bin\flutter-tizen", line 192, in <module>
    main()
  File "C:\Users\mos_s\flutter-tizen\bin\flutter-tizen", line 66, in main
    if targetFlutterVersion != revision(flutterDir):
  File "C:\Users\mos_s\flutter-tizen\bin\flutter-tizen", line 16, in revision
    return subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

**Comment by swift-kim** [comment]
Would you retry by removing the `flutter` directory inside the `flutter-tizen` directory and check if the problem persists?

**Comment by almog228** [comment]
> Would you retry by removing the `flutter` directory inside the `flutter-tizen` directory and check if the problem persists?

tnx! its work !
