### ISSUE TITLE
Unable to sign a native tpk in the WSL environment

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#146]
1. Install Tizen Studio using the CLI installer and install required packages.
1. Create a Tizen certificate.<p>
   ```sh
   tizen certificate -a abc -p abcdef -f abc
   ```
1. Create a security profile from it.<p>
   ```sh
   tizen security-profiles add -n abc -a $HOME/tizen-studio-data/keystore/author/abc.p12 -p abcdef
   ```
1. Create an app project with the `--tizen-language cpp` option and build it. The following error will be generated.

```
$ flutter-tizen build tpk --device-profile wearable

💪 Building with sound null safety 💪

The abc profile is used for signing.
Building a Tizen application in release mode...                     8.5s
Failed to generate TPK:
Initialize... OK
Copying files... OK
Signing... java.io.IOException: keystore password was incorrect
error occured on packaging.

javax.xml.transform.TransformerException: Unable to evaluate expression using this context
        at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:370)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(XPathImpl.java:209)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:271)
        at org.tizen.ncli.subcommands.packages.NativeProject.getProjectName(NativeProject.java:65)
        at org.tizen.ncli.subcommands.packages.PackageNativeCLICommand.getEnv(PackageNativeCLICommand.java:336)
        at org.tizen.ncli.subcommands.packages.PackageNativeCLICommand.call(PackageNativeCLICommand.java:84)
        at org.tizen.ncli.subcommands.packages.PackageNativeCLICommand.call(PackageNativeCLICommand.java:48)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.PackageCLI.doPackageForTpk(PackageCLI.java:1155)
        at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1260)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:188)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:121)
Caused by: java.lang.RuntimeException: Unable to evaluate expression using this context
        at com.sun.org.apache.xpath.internal.axes.NodeSequence.setRoot(NodeSequence.java:266)
        at com.sun.org.apache.xpath.internal.axes.LocPathIterator.execute(LocPathIterator.java:214)
        at com.sun.org.apache.xpath.internal.XPath.execute(XPath.java:341)
        ... 12 more
```

Note: No error occurs when signing a tpk with the default certificate (without creating a security profile). The error occurs only when you have any active profile.

**Comment by swift-kim** [comment]
This error could be related to the error in https://github.com/flutter-tizen/flutter-tizen/issues/79#issuecomment-848106353 reported by @allan175.
