### ISSUE TITLE
Flutter doctor check crashed

### ISSUE THREAD

**Issue by dkrutskikh** [flutter-tizen/flutter-tizen#309]
Hi flutter-tizen team! Every run of `flutter-tizen doctor` I faced this issue:

```
flutter-tizen doctor -v  
[☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Null check operator used on a null value
    • #0      TizenArtifacts.getArtifactPath (package:flutter_tizen/tizen_artifacts.dart:52:53)
      #1      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:465:47)
      #2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #4      _rootRun (dart:async/zone.dart:1428:13)
      #5      _CustomZone.run (dart:async/zone.dart:1328:19)
      #6      _runZoned (dart:async/zone.dart:1863:10)
      #7      runZonedGuarded (dart:async/zone.dart:1851:12)
      #8      runZoned (dart:async/zone.dart:1782:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #16     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #22     main (package:flutter_tizen/executable.dart:93:3)
      <asynchronous suspension>


[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision ff8141bf44 (3 days ago), 2022-01-03 11:31:42 +0900
    • Engine revision c8a9118512
    • Tizen Studio 4.5.1 at /Users/dmitry/tizen-studio
    • .NET SDK 6.0.101 at /usr/local/share/dotnet/dotnet

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dmitry/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Users/dmitry/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/dmitry/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
```

but `flutter doctor` works fine for me:

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-RU)
    • Flutter version 2.8.1 at /Users/dmitry/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dmitry/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Users/dmitry/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/dmitry/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7935034/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
```

**Comment by swift-kim** [comment]
Thank you for reporting! This is a bug that has been introduced by a [recent commit](https://github.com/flutter-tizen/flutter-tizen/pull/305).

Will be fixed by #310. Tests will be added later.
