### ISSUE TITLE
Question: Reason that "flutter-tizen run" fails

### ISSUE THREAD

**Issue by zCode93** [flutter-tizen/flutter-tizen#440]
Command **flutter-tizen run** fails with exception:

```
Exception: Failed to build C++ embedding:
Total time: 00:00:00.257
Building a Tizen application in debug mode...                       9.8s
Exception: The build failed
```

What could be the reason for this ?
_Note: Trying to run it on Tizen T-samsung-6.5-x86 TV._

**Comment by swift-kim** [comment]
Is the file `embedding/cpp/project_dep.prop` present in your flutter-tizen installation directory?

**Comment by zCode93** [comment]
@swift-kim If you mean `embedding\cpp\project.def.prop` , Yes it does exist.

@bbrto21 I've ran the command with -v option, kindly check attached txt file for full log.
[Log.txt](https://github.com/flutter-tizen/flutter-tizen/files/9594020/Log.txt)

**Comment by swift-kim** [comment]
Unfortunately I have no idea how to reproduce the issue. Please try reinstalling flutter-tizen and Tizen Studio, and share the `flutter-tizen doctor -v` result if the problem persists. Otherwise you might just remove Tizen plugin dependencies from your app's `pubspec.yaml` if you don't need them.

**Comment by bbrto21** [comment]
@zCode93
Hmml, in general, flutter-tizen tells you what's wrong with your host environment.. 
but this case, I can't find any clue from log
Is the Gcc 9.2 toolchain installed? (you can install it using package-manger in tizen sdk)

**Comment by swift-kim** [comment]
Please let us know if the problem still persists.

**Comment by Blacktaler** [comment]
I'm having the same problem:
target: tizen_cpp_embedding
exception:Error: Failed to build C++ embedding:
Exception in thread "main" java.lang.NoClassDefFoundError: org/tizen/sbilib/for_cli/sbiplugin/SBIPluginManager
        at org.tizen.ncli.subcommands.build.buildnative.BuildNativeCLICommand.call(BuildNativeCLICommand.java:198)
        at org.tizen.ncli.subcommands.build.buildnative.BuildNativeCLICommand.call(BuildNativeCLICommand.java:48)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.BuildNativeCLI.execute(BuildNativeCLI.java:107)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:190)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:123)
Caused by: java.lang.ClassNotFoundException: org.tizen.sbilib.for_cli.sbiplugin.SBIPluginManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 more
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      NativeEmbedding.build (package:flutter_tizen/build_targets/embedding.dart:124:7)
...

running **flutter-tizen doctor -v** does not show any issue
