### ISSUE TITLE
command not found Error 127

### ISSUE THREAD

**Issue by nassimus26** [flutter-tizen/flutter-tizen#441]
I create a simple project `myapp`, when I run  `flutter-tizen run`

I got this error at the end "`command not found.... Error 127`"

And the verbose info shows this line :

`[  +15 ms] executing: C:\tizen-studio\tools\ide\bin\tizen.bat build-native -C Debug -a x86 -c llvm-10.0 -d TV_PROFILE -e -fPIC -r wearable-4.0-emulator.flutter -- C:\work\flutter-tizen\embedding\cpp`

I am not trying to build for a wearable device but for a TV  device I tried with `--device-profile tv` , but it didn't work

```
PS C:\Users\cd_bo\StudioProjects\myapp> flutter-tizen doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.3.0, on Microsoft Windows [version 10.0.19044.2006], locale fr-FR)
    ! Flutter version 3.3.0 on channel unknown at C:\work\flutter-tizen\flutter
    ! Upstream repository unknown
[√] Tizen toolchain - develop for Tizen devices
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.67.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```
```

! Doctor found issues in 1 category.
PS C:\Users\cd_bo\StudioProjects\myapp> flutter-tizen doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.3.0, on Microsoft Windows [version 10.0.19044.2006], locale fr-FR)
    ! Flutter version 3.3.0 on channel unknown at C:\work\flutter-tizen\flutter
    ! Upstream repository unknown
[√] Tizen toolchain - develop for Tizen devices
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.67.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
PS C:\Users\cd_bo\StudioProjects\myapp> flutter-tizen -v run
[ +130 ms] executing: [C:\work\flutter-tizen\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +124 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ffccd96b62ee8cec7740dab303538c5fc26ac543
[        ] executing: [C:\work\flutter-tizen\flutter/] git tag --points-at ffccd96b62ee8cec7740dab303538c5fc26ac543
[  +98 ms] Exit code 0 from: git tag --points-at ffccd96b62ee8cec7740dab303538c5fc26ac543
[        ] 3.3.0
[  +52 ms] executing: [C:\work\flutter-tizen\flutter/] git rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] HEAD
[   +2 ms] executing: [C:\work\flutter-tizen\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +89 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[ +898 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] Artifact Instance of 'TizenEngineArtifacts' is not required, skipping update.
[  +12 ms] executing: C:\Users\cd_bo\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +44 ms] executing: C:\tizen-studio\tools\sdb.exe devices
[ +105 ms] List of devices attached
[  +19 ms] List of devices attached
           emulator-26101       device          T-samsung-6.5-x86
[   +2 ms] executing: C:\tizen-studio\tools\sdb.exe -s emulator-26101 capability
[  +72 ms] Exit code 0 from: C:\tizen-studio\tools\sdb.exe -s emulator-26101 capability
[        ] secure_protocol:enabled
           intershell_support:disabled
           filesync_support:pushpull
           usbproto_support:disabled
           sockproto_support:enabled
           syncwinsz_support:enabled
           sdbd_rootperm:disabled
           rootonoff_support:disabled
           encryption_support:disabled
           zone_support:disabled
           multiuser_support:enabled
           cpu_arch:x86
           sdk_toolpath:/home/owner/share/tmp/sdk_tools
           profile_name:tv
           vendor_name:Samsung
           can_launch:tv-samsung
           device_name:Tizen
           platform_version:6.5
           product_version:4.0
           sdbd_version:2.2.31
           sdbd_plugin_version:3.8.5_EM_REL
           sdbd_cap_version:1.0
           log_enable:disabled
           log_path:/tmp
           appcmd_support:disabled
           appid2pid_support:enabled
           pkgcmd_debugmode:enabled
           netcoredbg_support:enabled
           architecture:32
           platform_build_version:6.5
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] Skipping pub get: version match.
[ +312 ms] Generating C:\Users\cd_bo\StudioProjects\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +105 ms] Using hardware rendering with device Tizen T-samsung-6.5-x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[ +121 ms] Initializing file store
[  +52 ms] Skipping target: gen_localizations
[  +35 ms] Skipping target: _composite
[  +11 ms] complete
[  +45 ms] Launching tizen\flutter\generated_main.dart on Tizen T-samsung-6.5-x86 in debug mode...
[  +25 ms] C:\work\flutter-tizen\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\work\flutter-tizen\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\work\flutter-tizen\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\cd_bo\AppData\Local\Temp\flutter_tools.36a138d7\flutter_tool.129685b\app.dill --packages C:\Users\cd_bo\StudioProjects\myapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[ +132 ms] <- compile file:///C:/Users/cd_bo/StudioProjects/myapp/tizen/flutter/generated_main.dart
[  +37 ms] Building TPK
[  +55 ms] Building a Tizen application in debug mode...
[  +22 ms] Initializing file store
[  +71 ms] Done initializing file store
[ +162 ms] Skipping target: gen_localizations
[  +54 ms] Skipping target: gen_dart_plugin_registrant
[  +83 ms] tizen_cpp_embedding: Starting due to {}
[  +49 ms] TV SDK could not be found.
[   +2 ms] Found a rootstrap: wearable-4.0-emulator.core
[  +15 ms] executing: C:\tizen-studio\tools\ide\bin\tizen.bat build-native -C Debug -a x86 -c llvm-10.0 -d TV_PROFILE -e -fPIC -r wearable-4.0-emulator.flutter -- C:\work\flutter-tizen\embedding\cpp
[ +997 ms] Skipping target: kernel_snapshot
[+4919 ms] [PLATFORM] Tizen-4.0
                    [ARCHITECTURE] i586
                    [COMPILER] LLVM-10.0
                    [CONFIGURATION] Debug
                    [SBI] prdefine options = -DTV_PROFILE
                    [SBI] command : cmd /c make.exe -f "C:\tizen-studio\tools\ide\resources\native\Build\makefile" -r
                    C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -f C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk
                    /usr/bin/sh: C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make.exe: command not found
                    make: *** [C:\tizen-studio\tools\ide\resources\native\Build\makefile:27: app_build] Error 127
                    Total time: 00:00:00.706
[   +4 ms] Persisting file store
[  +11 ms] Done persisting file store
[   +7 ms] Exception: Failed to build C++ embedding:
           [PLATFORM] Tizen-4.0
           [ARCHITECTURE] i586
           [COMPILER] LLVM-10.0
           [CONFIGURATION] Debug
           [SBI] prdefine options = -DTV_PROFILE
           [SBI] command : cmd /c make.exe -f "C:\tizen-studio\tools\ide\resources\native\Build\makefile" -r 
           C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe -f C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk
           /usr/bin/sh: C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make.exe: command not found
           make: *** [C:\tizen-studio\tools\ide\resources\native\Build\makefile:27: app_build] Error 127
           Total time: 00:00:00.706
[  +20 ms] Building a Tizen application in debug mode... (completed in 6,4s)
[+6349 ms] Exception: The build failed.
[   +7 ms] "flutter run" took 14 815ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tizen/executable.dart:94:3)
           <asynchronous suspension>
           
           
[   +2 ms] ensureAnalyticsSent: 0ms
[        ] Running shutdown hooks
[   +5 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS C:\Users\cd_bo\StudioProjects\myapp>

```

**Comment by nassimus26** [comment]
Hi it works after executing `choco uninstall make` , I think it was making a conflict with the gcc build

**Comment by swift-kim** [comment]
Thank you for reporting. We're currently appending the `msys2\usr\bin` path to the end of user's PATH environment variable and it should be the cause of the error.

https://github.com/flutter-tizen/flutter-tizen/blob/8ac3e60b5d652c0319a968dd22a981cc18eb475b/lib/tizen_sdk.dart#L140

I'll change the order so that things always work as expected.

By the way, did you add any plugin dependency in your `pubspec.yaml`?

**Comment by nassimus26** [comment]
If I just need to add these ".so" libraries to the build, please show me how, I didn't find this in your documentation.

**Comment by nassimus26** [comment]
https://github.com/flutter-tizen/flutter-tizen/issues/442

**Comment by swift-kim** [comment]
@nassimus26 Thank you for the clarification!

> is it an Android apk, or probably a native C app?

The flutter-tizen tool by default builds your app into a .NET TPK. You will find some C# code in the `tizen` directory of your app project.

> If I just need to add these ".so" libraries to the build, please show me how

I answered in detail in https://github.com/flutter-tizen/flutter-tizen/issues/442.
