### ISSUE TITLE
[TV emulator] "Unhandled exception: System.DllNotFoundException" on first launch of an app

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#50]
```
I/ConsoleMessage(10510): FlutterApplication.cs: OnCreate(54) > switches: --enable-dart-profiling --enable-checked-mode
E/ConsoleMessage(10510): FlutterApplication.cs: Run(39) > Unhandled exception: System.DllNotFoundException: Unable to load shared library 'flutter_engine.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libflutter_engine.so: cannot open shared object file: No such file or directory
E/ConsoleMessage(10510):    at Tizen.Flutter.Embedding.Interop.FlutterEngineRunsAOTCompiledDartCode()
E/ConsoleMessage(10510):    at Tizen.Flutter.Embedding.FlutterApplication.OnCreate()
E/ConsoleMessage(10510):    at Runner.App.OnCreate()
E/ConsoleMessage(10510):    at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
E/ConsoleMessage(10510):    at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
E/ConsoleMessage(10510):    at Tizen.Applications.CoreApplication.Run(String[] args)
E/ConsoleMessage(10510):    at Tizen.Applications.CoreUIApplication.Run(String[] args)
E/ConsoleMessage(10510):    at Tizen.Flutter.Embedding.FlutterApplication.Run(String[] args)
E/ConsoleMessage(10510):    at Runner.App.Main(String[] args)
```

The reason is still unknown but it may have something to do with the Linux kernel used by TV emulators.

A temporary solution:
1. Change the `api-version` value in `tizen/tizen-manifest.xml` file to something different (e.g. 4.0 → 6.0)
2. Launch the app (`flutter-tizen run`)
3. Change the value back to the original value (the error will not be generated on successive launches after the app launches successfully at least once)

**Comment by swift-kim** [comment]
Another workaround is just to install the same TPK twice if the package has previously not been installed on the device. I'll open a PR with the patch.
