### ISSUE TITLE
Building Tizen TV app TPK gives error on Mac

### ISSUE THREAD

**Issue by sam-nixplay** [flutter-tizen/flutter-tizen#513]
I am trying to build a Tizen tv app with flutter-tizen on a Macbook M2, however I am getting:

```
Exception: Failed to build C++ embedding:
           Total time: 00:00:00.356
[   +5 ms] Building a Tizen application in release mode... (completed in 2,382ms)
[        ] "flutter tpk" took 2,928ms.
[   +1 ms] The build failed.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:109:9)
           <asynchronous suspension>
           #2      BuildTpkCommand.runCommand (package:flutter_tizen/commands/build.dart:86:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tizen/executable.dart:83:3)
           <asynchronous suspension>
```

It is not giving me much more information than this. My flutter-tizen doctor -v gives:

```
[!] Flutter (Channel unknown, 3.10.1, on macOS 13.5.1 22G90 darwin-arm64, locale en-PH)
    ! Flutter version 3.10.1 on channel unknown at /Users/sam/flutter-tizen/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Warning: `flutter` on your path resolves to /Users/sam/fvm/versions/3.10.5/bin/flutter, which is not inside your current
      Flutter SDK checkout at /Users/sam/flutter-tizen/flutter. Consider adding /Users/sam/flutter-tizen/flutter/bin to the
      front of your path.
    ! Warning: `dart` on your path resolves to /Users/sam/fvm/versions/3.10.5/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/sam/flutter-tizen/flutter. Consider adding /Users/sam/flutter-tizen/flutter/bin to the
      front of your path.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision d3d8effc68 (4 months ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision 1861b50d94 (3 months ago), 2023-06-19 16:03:08 +0900
    • Engine revision 439a83231a
    • Tizen Studio 5.1 at /Users/sam/tizen-studio
    • .NET SDK 7.0.306 at /usr/local/share/dotnet/dotnet

Error executing simctl: 69
You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to
review and agree to the Xcode and Apple SDKs license.


[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/sam/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    ✗ Xcode end user license agreement not signed; open Xcode or run the command 'sudo xcodebuild -license'.
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to
        invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.
```

**Comment by swift-kim** [comment]
I had no problem building the C++ embedding on my M1 Macbook.

```sh
swift@MacBookAir:~/Git/dummy/some_plugin/example$ flutter-tizen build tpk -ptv
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1284 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
The swift profile is used for signing.
Building a Tizen application in release mode...                    30.9s
✓ Built build/tizen/tpk/com.example.some_plugin_example-1.0.0.tpk (7.3MB).
```
```
[!] Flutter (Channel unknown, 3.10.1, on macOS 13.1 22C65 darwin-arm64, locale ko-KR)
    ! Flutter version 3.10.1 on channel unknown at /Users/swift/Git/flutter-tizen/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision d3d8effc68 (4 months ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Tizen toolchain - develop for Tizen devices
    • Framework revision 1861b50d94 (3 months ago), 2023-06-19 16:03:08 +0900
    • Engine revision 439a83231a
    • Tizen Studio 5.1 at /Users/swift/tizen-studio
    • .NET SDK 6.0.101 at /usr/local/share/dotnet/dotnet
```

Could you retry after cleaning up any caches? (e.g. run `git clean -xdf` inside the flutter-tizen installation directory.)

**Comment by sam-nixplay** [comment]
`Could you retry after cleaning up any caches? (e.g. run git clean -xdf inside the flutter-tizen installation directory.)` I tried this and still have the same exact error. Even with a completely new created project by flutter-tizen I get this error.

```
tizen_example flutter-tizen build tpk -ptv --verbose
[  +46 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[ +199 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping
update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'TizenEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'TizenEmbedderArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[   +5 ms] Skipping pub get: version match.
[  +73 ms] Generating
/Users/sam/Documents/Development/Flutter/tizen_example/android/app/src/main/java/io/
flutter/plugins/GeneratedPluginRegistrant.java
[  +16 ms] Building a Tizen application in release mode...
[        ] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +3 ms] Skipping target: gen_dart_plugin_registrant
[        ] tizen_cpp_embedding: Starting due to {}
[   +3 ms] TV SDK could not be found.
[        ] Found a rootstrap: wearable-5.5-device.core
[        ] executing: /Users/sam/tizen-studio/tools/ide/bin/tizen build-native -C
Release -a arm -c llvm-10.0 -d TV_PROFILE -e -fPIC -r wearable-5.5-device.flutter --
/Users/sam/flutter-tizen/embedding/cpp
[        ] kernel_snapshot: Starting due to {}
[   +3 ms] /Users/sam/flutter-tizen/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/Users/sam/flutter-tizen/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.da
rt.snapshot --sdk-root
/Users/sam/flutter-tizen/flutter/bin/cache/artifacts/engine/common/flutter_patched_s
dk_product/ --target=flutter --no-print-incremental-dependencies
-Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --target-os android
--packages
/Users/sam/Documents/Development/Flutter/tizen_example/.dart_tool/package_config.jso
n --output-dill
/Users/sam/Documents/Development/Flutter/tizen_example/.dart_tool/flutter_build/ddcc
e79bd9985e6aba5ec42fb5717dd6/app.dill --depfile
/Users/sam/Documents/Development/Flutter/tizen_example/.dart_tool/flutter_build/ddcc
e79bd9985e6aba5ec42fb5717dd6/kernel_snapshot.d --verbosity=error
file:///Users/sam/Documents/Development/Flutter/tizen_example/tizen/flutter/generate
d_main.dart
[+5647 ms] kernel_snapshot: Complete
[ +206 ms] tizen_aot_elf: Starting due to {InvalidatedReasonKind.inputChanged: The
following inputs have updated contents:
/Users/sam/Documents/Development/Flutter/tizen_example/.dart_tool/flutter_build/ddcc
e79bd9985e6aba5ec42fb5717dd6/app.dill,/Users/sam/flutter-tizen/flutter/bin/internal/
engine.version,/Users/sam/flutter-tizen/flutter/bin/internal/engine.version,/Users/s
am/flutter-tizen/flutter/bin/internal/engine.version}
[   +2 ms] targetingApplePlatform = false
[        ] extractAppleDebugSymbols = true
[        ] Will strip AOT snapshot during build.
[        ] executing:
/Users/sam/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-arm-release/darwin
-x64/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=/Users/sam/Documents/Development/Flutter/tizen_example/.dart_tool/flutter_buil
d/ddcce79bd9985e6aba5ec42fb5717dd6/app.so --strip --no-sim-use-hardfp
--no-use-integer-division
/Users/sam/Documents/Development/Flutter/tizen_example/.dart_tool/flutter_build/ddcc
e79bd9985e6aba5ec42fb5717dd6/app.dill
[+2583 ms] Total time: 00:00:00.399
[ +371 ms] tizen_aot_elf: Complete
[  +18 ms] Persisting file store
[   +2 ms] Done persisting file store
[   +2 ms] Exception: Failed to build C++ embedding:
           Total time: 00:00:00.399
[   +4 ms] Building a Tizen application in release mode... (completed in 8.9s)
[        ] "flutter tpk" took 9,150ms.
[   +1 ms] The build failed.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TizenBuilder.buildTpk
(package:flutter_tizen/tizen_builder.dart:109:9)
           <asynchronous suspension>
           #2      BuildTpkCommand.runCommand
(package:flutter_tizen/commands/build.dart:86:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand
(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tizen/executable.dart:83:3)
           <asynchronous suspension>
           
           
[  +16 ms] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by swift-kim** [comment]
The problem is that the following Tizen CLI command fails for some unknown reason. The command should fail (printing only `Total time: ...`) even if you run it manually from the command line.
```sh
USER_CPP_OPTS="-std=c++17" /Users/sam/tizen-studio/tools/ide/bin/tizen build-native -C Release -a arm -c llvm-10.0 -d TV_PROFILE -e "-fPIC" -r wearable-5.5-device.flutter -- /Users/sam/flutter-tizen/embedding/cpp
```
The Tizen CLI builder does not give any information about the error so it's really hard to debug the problem. A typical cause of the error is specifying an invalid rootstrap ID (`wearable-5.5-device.flutter`), but I believe you already have the `~/tizen-studio/tools/smart-build-interface/plugins/flutter-rootstrap.xml` file that looks like:
```xml
<?xml version="1.0"?>
<extension point="rootstrapDefinition">
  <rootstrap id="wearable-5.5-device.flutter" name="Flutter" version="Tizen 5.5" architecture="armel" path="/Users/sam/tizen-studio/platforms/tizen-5.5/wearable/rootstraps/wearable-5.5-device.core" supportToolchainType="tizen.core">
    <property key="DEV_PACKAGE_CONFIG_PATH" value="/Users/sam/tizen-studio/platforms/tizen-5.5/wearable/rootstraps/info/wearable-5.5-device.core.dev.xml"/>
    <property key="LINKER_MISCELLANEOUS_OPTION" value="-static-libstdc++"/>
    <property key="COMPILER_MISCELLANEOUS_OPTION" value=""/>
    <toolchain name="gcc" version="9.2"/>
  </rootstrap>
</extension>
```
Technically you don't need this step (building the native embedding) if you're writing a pure Dart app, but you will eventually need it if you depend on any native plugin in your app. One last thing you could try is to uninstall and reinstall Tizen Studio, but I'm not 100% sure if this will fix the problem.

**Comment by sam-nixplay** [comment]
@swift-kim I was able to run it on another Macbook but with Intel chip, one difference was that I did a CLI install of Tizen studio and it seems that that did the trick. After a re-install with CLI on my M2 Macbook, it now works without any problems. Thank you for the assitance!

**Comment by sam-nixplay** [comment]
@swift-kim maybe I did something wrong before with the GUI installation and it got corrupted as the agreement to T&C was hard to do. With the CLI it is very clear and straightforward anyway. And the flutter-tizen doctor gives an indication on what is missing
