### ISSUE TITLE
Support tizen 8.0 emulator

### ISSUE THREAD

**Issue by JSUYA** [flutter-tizen/flutter-tizen#538]
A crash occurs when running the flutter-tizen app on the emulator of the common unified profile of Tizen 8.0.

https://developer.tizen.org/blog/announcing-tizen-studio-5.5-release?langredirect=1
```
  - Added common unified profile called Tizen and deprecated mobile and wearable profiles from Tizen 8.0 version onwards.
```

log
```
E/ConsoleMessage(11271): FlutterApplication.cs: Run(131) > Unhandled exception: System.DllNotFoundException: Unable to load shared library 'flutter_tizen.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libflutter_tizen.so.so: cannot open shared object file: No such file or directory
E/ConsoleMessage(11271):    at Tizen.Flutter.Embedding.Interop.FlutterDesktopEngineCreate(FlutterDesktopEngineProperties& engine_properties)
E/ConsoleMessage(11271):    at Tizen.Flutter.Embedding.FlutterEngine..ctor(String assetsPath, String icuDataPath, String aotLibraryPath, String dartEntrypoint, List`1 dartEntrypointArgs) in /home/junsu/dev/os/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs:line 50
E/ConsoleMessage(11271):    at Tizen.Flutter.Embedding.FlutterEngine..ctor(String dartEntrypoint, List`1 dartEntrypointArgs) in /home/junsu/dev/os/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterEngine.cs:line 22
E/ConsoleMessage(11271):    at Tizen.Flutter.Embedding.FlutterApplication.OnCreate() in /home/junsu/dev/os/f-project/flutter-tizen/embedding/csharp/Tizen.Flutter.Embedding/FlutterApplication.cs:line 152
E/ConsoleMessage(11271):    at Runner.App.OnCreate() in /home/junsu/dev/os/f-project/dev/test_cs_14/tizen/App.cs:line 9
E/ConsoleMessage(11271):    at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data) in Tizen.Applications.UI.dll:token 0x6000011+0x44

```

**Comment by JSUYA** [comment]
https://github.com/flutter-tizen/flutter-tizen/pull/537
