### ISSUE TITLE
Flutter-tizen run not working....

### ISSUE THREAD

**Issue by Akash4097** [flutter-tizen/flutter-tizen#547]
i am testing flutter-tizen apps on smart-tv emulator...

i  create a dem project and try to run on the emulator, but it won't run and give me following error:

```
target: tizen_cpp_embedding
exception:Error: The rootstrap iot-headed-6.0-emulator.core could not be found.
To install missing package(s), run:
C:\tizen-studio\package-manager\package-manager-cli.exe install IOT-Headed-6.0-NativeAppDevelopment-CLI
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      TizenSdk.getFlutterRootstrap (package:flutter_tizen/tizen_sdk.dart:309:7)
#2      NativeEmbedding.build (package:flutter_tizen/build_targets/embedding.dart:103:43)
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:27)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#11     TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:104:11)
<asynchronous suspension>
#12     TizenDevice.startApp (package:flutter_tizen/tizen_device.dart:352:7)
<asynchronous suspension>
#13     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:476:33)
<asynchronous suspension>
#14     HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:432:14)
<asynchronous suspension>
#15     Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#16     HotRunner.run (package:flutter_tools/src/run_hot.dart:463:34)
<asynchronous suspension>
#17     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:808:27)
<asynchronous suspension>
#18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#20     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#26     main (package:flutter_tizen/executable.dart:84:3)
<asynchronous suspension>


Building a Tizen application in debug mode...                      10.9s
Error: The build failed.
```
although the pkg mentioned in the error i already have installed, even i uninstall and reinstall it again...but facing the same error again and again....anybody please guide me on this issue. Thanks.

**Comment by swift-kim** [comment]
Looks like a bug recently introduced by https://github.com/flutter-tizen/flutter-tizen/commit/7ea290160204ec40dc63232a689ca39e981e6ed7. Should have been fixed by https://github.com/flutter-tizen/flutter-tizen/commit/fc554a750d8f5d942b33b8eea16532bbbcd6c96a. Please update your flutter-tizen installation. The tool will now require you to install the Mobile 6.0 SDK package instead of IoT-Headed 6.0.

**Comment by Akash4097** [comment]
after update to latest, previous error gone but face the following issue....

```
flutter-tizen run                                                          in pwsh at 14:03:18
Launching tizen\flutter\generated_main.dart on Tizen T-samsung-8.0-x86 in debug mode...
The akash profile is used for signing.
Building a Tizen application in debug mode...                      50.3s
✓ Built build\tizen\tpk\com.example.demo-1.0.0.tpk (28.8MB).
Installing build\tizen\tpk\com.example.demo-1.0.0.tpk...           12.2s
Installing TPK failed:
WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
pushed     com.example.demo-1.0.0.tpk     0%          0MB           0KB/spushed     com.example.demo-1.0.0.tpk    1%         0MB
0KB/spushed     com.example.demo-1.0.0.tpk       21%          6MB        3988KB/spushed     com.example.demo-1.0.0.tpk  34%           9MB
4206KB/spushed     com.example.demo-1.0.0.tpk    41%         12MB        3392KB/spushed     com.example.demo-1.0.0.tpk  55%
15MB     2689KB/spushed     com.example.demo-1.0.0.tpk   62%         18MB        3543KB/spushed     com.example.demo-1.0.0.tpk   76%
22MB     3005KB/spushed     com.example.demo-1.0.0.tpk   83%         24MB        3488KB/spushed     com.example.demo-1.0.0.tpk   98%
28MB     3036KB/spushed     com.example.demo-1.0.0.tpk  100%         28MB        3036KB/s
1 file(s) pushed. 0 file(s) skipped.
G:\projects\tizen\demo\build\tizen\tpk\com.example.demo-1.0.0.tpk   2891KB/s (30247062 bytes in 10.214s)

install com.example.demo
package_path /home/owner/share/tmp/sdk_tools/com.example.demo-1.0.0.tpk
app_id[com.example.demo] install start
app_id[com.example.demo] installing[10]
app_id[com.example.demo] installing[21]
app_id[com.example.demo] install failed[118, -12], reason: Check certificate error :
spend time for wascmd is [1832]ms
Error launching application on Tizen T-samsung-8.0-x86.
```
please help on this...

**Comment by JSUYA** [comment]
Please refer to [this](https://github.com/flutter-tizen/flutter-tizen/wiki/TPK-installation-troubleshooting#known-errors).

**Comment by Akash4097** [comment]
> Please refer to [this](https://github.com/flutter-tizen/flutter-tizen/wiki/TPK-installation-troubleshooting#known-errors).

i am trying to test the app on TV emulator so samsung certificate won't required, so i created tizen certificate... but still got the same problem...which step i miss?? can you please help me.

**Comment by JSUYA** [comment]
I checked that the same problem occurred when I created and tested a new project and tizen certificate in the TV emulator(8.0).

```
 $ flutter-tizen run
Launching tizen/flutter/generated_main.dart on Tizen t-0516-1 in debug mode...
The test_tizen_certi profile is used for signing.
Building a Tizen application in debug mode...                      19.8s
✓ Built build/tizen/tpk/com.example.test_cs_22-1.0.0.tpk (28.8MB).
Installing build/tizen/tpk/com.example.test_cs_22-1.0.0.tpk...         4.1s
Installing TPK failed:
WARNING: Your data are to be sent over an unencrypted connection and could be read by others.
pushed com.example.test_cs_22-1.0.0.tpk100%	     28MB	    0KB/s
1 file(s) pushed. 0 file(s) skipped.
/home/junsu/dev/os/f-project/dev/test_cs_22/build/tizen/tpk/com.example.test_cs_22-1.0.0.tpk   67967KB/s (30225930 bytes in 0.434s)

install com.example.test_cs_22
package_path /home/owner/share/tmp/sdk_tools/com.example.test_cs_22-1.0.0.tpk
app_id[com.example.test_cs_22] install start
app_id[com.example.test_cs_22] installing[10]
app_id[com.example.test_cs_22] installing[21]
app_id[com.example.test_cs_22] install failed[118, -12], reason: Check certificate error :
spend time for wascmd is [3326]ms
Error launching application on Tizen t-0516-1.
```

However, I checked that it was working normally by creating it with samsung-cerificate and registering the DUID of the emulator.
How about using samsung-certificate? Maybe there are changes(?) in the 8.0 tv emulator or there are issues we haven't figured out yet. We will also update the wiki page.

**Comment by swift-kim** [comment]
My target profile was mobile/wearable when the document was written. The TV emulator is distributed directly by the manufacturer (Samsung VD) and is a little bit different from other types of emulators (which are distributed by the Tizen team). Let me update the document to avoid any confusion. Thanks!
