### ISSUE TITLE
video player avplay crash 

### ISSUE THREAD

**Issue by Akash4097** [flutter-tizen/flutter-tizen#550]
i am trying to build an app with video functionality only for TVs. so for that i create a simple app and follow what mentioned in video_player_avplay plugin github, but i got the following error:

```
target: tizen_native_plugins
exception:Error: Failed to build video_player_avplay plugin:
[PLATFORM] Mobile-6.0
[ARCHITECTURE] i586
[COMPILER] LLVM-10.0
[CONFIGURATION] Debug
[SBI] prdefine options = -DTV_PROFILE
[SBI] command : cmd /c make.exe -f "C:\tizen-studio\tools\ide\resources\native\Build\makefile" -r
make -f C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Entering directory
'/c/Users/akash/AppData/Local/Pub/Cache/hosted/pub.dev/video_player_avplay-0.4.2/tizen'
preparing to build src/drm_license_helper.cc
preparing to build src/drm_manager.cc
preparing to build src/drm_manager_proxy.cc
preparing to build src/ecore_wl2_window_proxy.cc
preparing to build src/media_player.cc
preparing to build src/media_player_proxy.cc
preparing to build src/messages.cc
preparing to build src/plus_player.cc
preparing to build src/video_player.cc
preparing to build src/video_player_tizen_plugin.cc
C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:164: warning: overriding recipe for target 'Debug'
C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:161: warning: ignoring old recipe for target 'Debug'
  Building file: src/drm_license_helper.cc
  Output Path ./Debug
  Invoking: C++ Compiler
  Building directory: Debug/src
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/drm_license_helper.cc" -o
"Debug/src/drm_license_helper.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc
-Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/drm_license_helper.cc
  Building file: src/drm_manager.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/drm_manager.cc" -o
"Debug/src/drm_manager.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc
-Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/drm_manager.cc
  Building file: src/drm_manager_proxy.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/drm_manager_proxy.cc" -o
"Debug/src/drm_manager_proxy.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc
-Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/drm_manager_proxy.cc
  Building file: src/ecore_wl2_window_proxy.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/ecore_wl2_window_proxy.cc" -o
"Debug/src/ecore_wl2_window_proxy.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc
-Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/ecore_wl2_window_proxy.cc
  Building file: src/media_player.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/media_player.cc" -o
"Debug/src/media_player.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc
-Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/media_player.cc
  Building file: src/media_player_proxy.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/media_player_proxy.cc" -o
"Debug/src/media_player_proxy.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc
-Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/media_player_proxy.cc
  Building file: src/messages.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/messages.cc" -o "Debug/src/messages.o"
-DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3
-D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name i586-linux-gnueabi-g++
-march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument -fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/messages.cc
  Building file: src/plus_player.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/plus_player.cc" -o
"Debug/src/plus_player.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc
-Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
In file included from src/plus_player.cc:5:
In file included from src/plus_player.h:15:
inc\plusplayer/plusplayer_wrapper.h:471:32: warning: 'GetTrackLanguageCode' has C-linkage specified, but returns
user-defined type 'std::string' (aka 'basic_string<char>') which is incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetTrackLanguageCode(PlusplayerRef player,
                               ^
inc\plusplayer/plusplayer_wrapper.h:478:51: warning: 'GetTrackInfo' has C-linkage specified, but returns incomplete type
'std::vector<plusplayer::Track>' which could be incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:481:51: warning: 'GetActiveTrackInfo' has C-linkage specified, but returns
incomplete type 'std::vector<plusplayer::Track>' which could be incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetActiveTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:507:32: warning: 'GetStreamingProperty' has C-linkage specified, but returns
user-defined type 'std::string' (aka 'basic_string<char>') which is incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetStreamingProperty(PlusplayerRef player,
                               ^
4 warnings generated.
  Finished building: src/plus_player.cc
  Building file: src/video_player.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/video_player.cc" -o
"Debug/src/video_player.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL  -Iinc -Isrc
-Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target i586-tizen-linux-gnueabi
-gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name
i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
  Finished building: src/video_player.cc
  Building file: src/video_player_tizen_plugin.cc
  Output Path ./Debug
  Invoking: C++ Compiler
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -c "src/video_player_tizen_plugin.cc" -o
"Debug/src/video_player_tizen_plugin.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DTV_PROFILE -DFLUTTER_PLUGIN_IMPL
-Iinc -Isrc -Iinc/plusplayer  -I"pch" -g3 -D_DEBUG -O0 -Wall -c -fmessage-length=0 -std=c++14 -target
i586-tizen-linux-gnueabi -gcc-toolchain "C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/"
-ccc-gcc-name i586-linux-gnueabi-g++ -march=i586 -Wno-gnu -fstack-protector-strong -Wno-unused-command-line-argument
-fdebug-default-version=3  -fPIC
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -Werror-implicit-function-declaration  -std=c++17
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
-Wp,@./Debug/objs/platform_incs_file.inc
In file included from src/video_player_tizen_plugin.cc:20:
In file included from src/plus_player.h:15:
inc\plusplayer/plusplayer_wrapper.h:471:32: warning: 'GetTrackLanguageCode' has C-linkage specified, but returns
user-defined type 'std::string' (aka 'basic_string<char>') which is incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetTrackLanguageCode(PlusplayerRef player,
                               ^
inc\plusplayer/plusplayer_wrapper.h:478:51: warning: 'GetTrackInfo' has C-linkage specified, but returns incomplete type
'std::vector<plusplayer::Track>' which could be incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:481:51: warning: 'GetActiveTrackInfo' has C-linkage specified, but returns
incomplete type 'std::vector<plusplayer::Track>' which could be incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::vector<plusplayer::Track> GetActiveTrackInfo(
                                                  ^
inc\plusplayer/plusplayer_wrapper.h:507:32: warning: 'GetStreamingProperty' has C-linkage specified, but returns
user-defined type 'std::string' (aka 'basic_string<char>') which is incompatible with C [-Wreturn-type-c-linkage]
PLUS_PLAYER_EXPORT std::string GetStreamingProperty(PlusplayerRef player,
                               ^
4 warnings generated.
  Finished building: src/video_player_tizen_plugin.cc
  Building target: Debug/libvideo_player_tizen_plugin.so
  Invoking: C/C++ Linker
"C:\tizen-studio\tools\smart-build-interface/../llvm-10/bin/clang++.exe" -o ./Debug/libvideo_player_tizen_plugin.so
@./Debug/target_objs.file  -lplusplayer-wrapper -lgstsubtitle_tvplus -lgstsubtitleparse_tvplus -lplusplayercore_tvplus
-ltracksource_tvplus -lplusplayer_tvplus -ldashplusplayer_tvplus -Llib/i586/6.0
-L"C:/Users/akash/AppData/Local/Pub/Cache/hosted/pub.dev/video_player_avplay-0.4.2/tizen/lib" -Wl,--no-undefined
-Wl,-rpath='$ORIGIN' -target i586-tizen-linux-gnueabi -gcc-toolchain
"C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/" -ccc-gcc-name i586-linux-gnueabi-g++
-march=i586 -Wl,-z,relro,--as-needed,-z,noseparate-code  -Xlinker --as-needed -shared -lpthread
--sysroot="C:/tizen-studio/tools/smart-build-interface/../../platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.c
ore" -LC:/tizen-studio/platforms/tizen-6.0/mobile/rootstraps/mobile-6.0-emulator.core/usr/lib
@./Debug/platform_libs.file
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/cpp_client_wrapper/include"
-I"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-common/public"
-I"/e/flutter-tizen/flutter/bin/cache/dart-sdk/include" -lflutter_tizen_tv
-L"/e/flutter-tizen/flutter/bin/cache/artifacts/engine/tizen-x86/6.0"
"/g/projects/tizen/demo/.dart_tool/flutter_build/7a993a09f696c6b2e9dd7f3479b2fb33/tizen_embedding/libembedding_cpp.a"
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -lplusplayer-wrapper
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -lgstsubtitle_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -lgstsubtitleparse_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -lplusplayercore_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -ltracksource_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -lplusplayer_tvplus
C:\tizen-studio\tools\smart-build-interface/../i586-linux-gnueabi-gcc-9.2/lib/gcc/i586-tizen-linux-gnueabi/9.2.0/../../.
./../i586-tizen-linux-gnueabi/bin\ld: cannot find -ldashplusplayer_tvplus
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: ***
[C:\tizen-studio\tools\ide\resources\native\Build/makefile.mk:155: Debug/libvideo_player_tizen_plugin.so] Error 1
C:\tizen-studio\tools\smart-build-interface\..\msys2\usr\bin\make[1]: Leaving directory
'/c/Users/akash/AppData/Local/Pub/Cache/hosted/pub.dev/video_player_avplay-0.4.2/tizen'
make: *** [C:\tizen-studio\tools\ide\resources\native\Build\makefile:27: app_build] Error 2
Total time: 00:00:29.465
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      NativePlugins.build (package:flutter_tizen/build_targets/plugins.dart:151:9)
<asynchronous suspension>
#2      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:9)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#6      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#8      TizenBuilder.buildTpk (package:flutter_tizen/tizen_builder.dart:104:11)
<asynchronous suspension>
#9      TizenDevice.startApp (package:flutter_tizen/tizen_device.dart:352:7)
<asynchronous suspension>
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:476:33)
<asynchronous suspension>
#11     HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:432:14)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#13     HotRunner.run (package:flutter_tools/src/run_hot.dart:463:34)
<asynchronous suspension>
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:808:27)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#23     main (package:flutter_tizen/executable.dart:84:3)
<asynchronous suspension>


Building a Tizen application in debug mode...                      56.5s
Error: The build failed.
```
the only thing which i don't understand on docs: 
```
Note that video_player_avplay uses a compiled dynamic library, the api-version is your TV version, change it in tizen-manifest.xml:

<manifest package="xxx" version="1.0.0" api-version="6.0">
```
what i need to do(metioned in above line).

please help me to resolve this issue. Thanks

**Comment by JSUYA** [comment]
video_player_avplay is only for TV device. please check readme.
https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_avplay

and

> the only thing which i don't understand on docs: 
> ```
> Note that video_player_avplay uses a compiled dynamic library, the api-version is your TV version, change it in tizen-manifest.xml:
> 
> <manifest package="xxx" version="1.0.0" api-version="6.0">
> ```
> what i need to do(metioned in above line).

> please help me to resolve this issue. Thanks

The value of the api-version attribute must be the same as the tizen version of the actual device.

**Comment by swift-kim** [comment]
@JSUYA The README is incorrect. The author of the package just copied the Limitations section from `video_player_videohole` :( The emulator support (experimental) is only for `video_player_videohole`, not `video_player_avplay`.

**Comment by swift-kim** [comment]
If you don't have a physical TV device, `video_player_videohole` is your only option. Note that the plugin has a limitation: it doesn't support playing a local video file, but only supports playing streaming content from the web. You will eventually need a physical device to develop an application for Tizen TV.

@xiaowei-guan @xuelian-bai Is my understanding about the difference between `video_player_videohole` and `video_player_avplay` correct? Can we clarify it in the READMEs?

**Comment by Akash4097** [comment]
> As far as I know, there is a remote testlab. But I haven't tested video_player_avplay using this, so I can't guarantee it will work. https://developer.samsung.com/remotetestlab/devices/

okay i'll try it.

**Comment by Akash4097** [comment]
> If you don't have a physical TV device, `video_player_videohole` is your only option. Note that the plugin has a limitation: it doesn't support playing a local video file, but only supports playing streaming content from the web. You will eventually need a physical device to develop an application for Tizen TV.
> 
> @xiaowei-guan @xuelian-bai Is my understanding about the difference between `video_player_videohole` and `video_player_avplay` correct? Can we clarify it in the READMEs?

yes you are absolutely right @swift-kim but before that i want to ensure that the plugins work fine or not otherwise my investment gone waste...and it also highly depend on client needs. 

From yours reply @JSUYA @swift-kim i am here close this issue. Once again thanks for your help.
